### ISSUE TITLE
ACE Spectator nach neu Verbindung 

### ISSUE THREAD

**Issue by SunnyTeater** [TaktiCool/Streamator#4]
### ArmA3 Version:
+ 1.84 (stable)

### Streamator Version:
+ x.xx

### Mods:
+ A list of the modifications you are running.
Bitte der PDF entnehmen, da doch ganz schön viele:
https://img.sunnyteater.de/Mods_W.pdf

### Description:
+ Beim ersten laden der Mission ist der Streamnator ohne Probleme einsatzbereit und tut was er soll.
Sobald man aus technischen oder anderen Gründen neu zum Server verbinden oder den Spectator Slot wechselt ist der ACE Spectator aktiv. 

### Steps to reproduce:
+ neu mit Server verbinden

### Where did the issue occur?
+ Dedicated Multiplayer

### RPT log file:
+ Add a link ([pastebin](http://pastebin.com/)) to the client and/or server RPT file.
Mission pbo:
https://img.sunnyteater.de/%5BGrpW%5D_BB32_Sandstorm_1v2.takistan.pbo

die letzten rpts:
https://img.sunnyteater.de/arma3_x64_2018-08-04_19-44-38.rpt
https://img.sunnyteater.de/arma3_x64_2018-08-04_20-08-27.rpt
https://img.sunnyteater.de/arma3_x64_2018-08-04_20-04-15.rpt

ja externe links, Github unterstütz nicht alle Formate :/

**Comment by jokoho48** [comment]
issue seem to be triggered by wrong CLib Call in init.sqf
