### ISSUE TITLE
Streamator Installation | Question

### ISSUE THREAD

**Issue by aebian** [TaktiCool/Streamator#5]
### ArmA3 Version:
+ stable

### Streamator Version:
+ latest

### Mods:
+ https://mods.gruppe-w.de/mods/mods/

### Description:
+ Can you please clarify where Streamator needs to be installed? 

Currently we have both CLib and Streamator on the Server only.

This is our call: https://gist.github.com/Aebian/2330c1f45f2e791fb0215959c52fce52

**Comment by simon84** [comment]
You need both installed on the server. But you have to wait until the loadModules functions is broadcasted to the client:
```
waitUntil {!isNil "CLib_fnc_loadModules"};
call CLib_fnc_loadModules;
```

**Comment by aebian** [comment]
So our call should be like this then?: https://gist.github.com/Aebian/2330c1f45f2e791fb0215959c52fce52

**Comment by simon84** [comment]
Looks correct
