### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by Krzmbrzl** [TaktiCool/Streamator#7]
https://github.com/TaktiCool/Streamator/blob/master/addons/Streamator/Spectator/fn_openSpectator.sqf#L200
and
https://github.com/TaktiCool/Streamator/blob/master/addons/Streamator/Spectator/fn_openSpectator.sqf#L210

Shouldn't this be a `setVariable` instead of a `getVariable`?

**Comment by jokoho48** [comment]
yes open a PR to fix pls
